name: 'Release Notes'
description: 'Generate Release Notes using the Github API and a Handlebars template'
author: 'Richard Fennell'
inputs:
  templateFile:
    required: true
    description: 'The path to the Handlebars template'
    default: 'template.md'
  outputfile:
    required: true
    description: 'The path to the generated release notes'
    default: 'releasenotes.md'
runs:
  using: 'node12'
  main: 'dist/index.js'
