name: 'Release Notes'
description: 'Generate Release Notes using the Github API and a Handlebars template'
author: 'Richard Fennell'
inputs:
  templateFile:
    required: true
    description: 'The path to the Handlebars template'
    default: 'template.md'
  outputFile:
    required: true
    default: 'releasenotes.md'
  extensionsFile:
    required: false
    description: 'The path to the an optional module of custom Handlebars functions'
    default: ''
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: 'edit'  
  color: 'blue'
